name: Build CI

on: [workflow_dispatch,push]

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: adopt
                  java-version: 21

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew build

            - name: Run Test Servers
              timeout-minutes: 5
              run: |
                ./gradlew fabric:runGametestServer &
                ./gradlew neoforge:runGametestServer &
                wait

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: build/libs
